version: "3.9"

services:
  quantumcoin:
    build:
      context: .
    container_name: quantumcoin-container
    ports:
      - "8080:8080"
    command: /usr/local/bin/quantumcoin
    tty: true

  node1:
    build:
      context: .
    container_name: quantumcoin-node1
    ports:
      - "8081:8080"
    command: /usr/local/bin/quantumcoin
    tty: true

  node2:
    build:
      context: .
    container_name: quantumcoin-node2
    ports:
      - "8082:8080"
    command: /usr/local/bin/quantumcoin
    tty: true